<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProductsByFamily($famId){
        $qb = $this->createQueryBuilder('p')
            ->where('p.family = :fam')
            ->andWhere('p.isHidden = false')
            ->orderBy('p.id', 'DESC')
            ->setParameter('fam',$famId);

        return $qb->getQuery()->getResult();
    }

    public function findAllActives(){
        $qb = $this->createQueryBuilder('p')
            ->where('p.isHidden = false')
            ->orderBy('p.id', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function findMixedProducts($number){
        $qb = $this->createQueryBuilder('p')
            ->andWhere('p.isHidden = false')
            ->setMaxResults($number);

        return $qb->getQuery()->getResult();
    }

    public function findLatestProducts($number){
        $qb = $this->createQueryBuilder('p')
            ->where('p.isHidden = false')
            ->orderBy('p.dateAdded', 'DESC')
            ->setMaxResults($number);

        return $qb->getQuery()->getResult();
    }

}
