<?php

namespace AppBundle\Repository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends \Doctrine\ORM\EntityRepository
{

    public function findNotDelivered(){
        $qb = $this->createQueryBuilder('p')
            ->where('p.isDelivered = false');
        return $qb->getQuery()->getResult();
    }

    public function findAllDelivered(){
        $qb = $this->createQueryBuilder('p')
            ->where('p.isDelivered = true');
        return $qb->getQuery()->getResult();
    }


}
