<?php

namespace AppBundle\Repository;

/**
 * SizeProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeProductRepository extends \Doctrine\ORM\EntityRepository
{
}
